const images = [
  {
    src: "https://i.imgur.com/1XMebMy.png",
    alt: "Horizon Apex Legends",
    name: "Horizon",
    price: 555,
    etsyLink: "",
    redBubbleLink: "",
    quote: "C'mon little Newtie, we've got work to do.",
    description:
      "Dr. Mary Somers, better know as Horizon. A famous scientist from the floating city of Olympus, she joined the Apex Games to fund time travel research in order to return to her young son, Newton",
  },

  {
    src: "https://i.imgur.com/g3xRphV.png",
    alt: "Pathfinder Apex Legends",
    name: "Pathfinder",
    price: 555,
    etsyLink: "",
    redBubbleLink: "",
    quote: `Losing isn't fun. That's why I don't do it.`,
    description: `Pathfinder is the picture of optimism. A MRVN (Mobile Robotic Versatile eNtity) modified to specialize in location scouting and surveying. His moniker is "Forward Scout”.`,
  },
  {
    src: "https://i.imgur.com/Ou5j9iu.png",
    alt: "Octane Apex Legends",
    name: "Octane",
    price: 555,
    etsyLink: "",
    redBubbleLink: "",
    quote: "Whoa…what a rush!",
    description: `Octavio Silva, also known by his alias Octane. As a renowned daredevil and competitor in the
    Apex Games, his moniker is “The Adrenaline Junkie”.`,
  },
  {
    src: "https://i.imgur.com/TxqzKwR.png",
    alt: "Valkyrie Apex Legends",
    name: "Valkyrie",
    price: 555,
    etsyLink: "",
    redBubbleLink: "",
    quote: "",
    description: "",
  },

  {
    src: "https://i.imgur.com/rE22NTN.png",
    alt: "Wattson Apex Legends",
    name: "Wattson",
    price: 555,
    etsyLink: "",
    redBubbleLink: "",
    quote: "",
    description: "",
  },
  {
    src: "https://i.imgur.com/UWo0FQD.png",
    alt: "Lifeline Apex Legends",
    name: "Lifeline",
    price: 555,
    etsyLink: "",
    redBubbleLink: "",
    quote: "",
    description: "",
  },

  {
    src: "https://i.imgur.com/S3R3JSw.png",
    alt: "Caustic Apex Legends",
    name: "Caustic",
    price: 555,
    etsyLink: "",
    redBubbleLink: "",
    quote: "",
    description: "",
  },
  {
    src: "https://i.imgur.com/XSdc7pN.png",
    alt: "Gibralter Apex Legends",
    name: "Gibraltar",
    price: 555,
    etsyLink: "",
    redBubbleLink: "",
    quote: "",
    description: "",
  },
  {
    src: "https://i.imgur.com/JXDbAfl.png",
    alt: "Vantage Apex Legends",
    name: "Vantage",
    price: 555,
    etsyLink: "",
    redBubbleLink: "",
    quote: "",
    description: "",
  },
];

export default images;
